apiVersion: v1
baseDomain: __DOMAIN__
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - ca-central-1a
      - ca-central-1b
      - ca-central-1d
      type: __COMPUTE_FLAVOR__
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - ca-central-1a
      - ca-central-1b
      - ca-central-1d
      type: __MASTER_FLAVOR__
  replicas: 3
metadata:
  creationTimestamp: null
  name: __CLUSTER_NAME__
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.73.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: __OCP_REGION__
publish: External
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKJ+Hpbp9Tyz0LhZ/psGMuf4tOGPNCnR+yiLz58WAM8p6Z3mk7aUU7muU73lx3UKzboQ/Bct0X8cBJOh9aXXBRa2aZxGfQj1x4Zxf4wUwIEev68WBxBCG+D3/N5V0AAD/SYsF0xymcUX0/fn0X94gKREHFbJDiaXNXPE+ohpKClunIp15VZnAxxBZYXzIwNp2EguvTbOMBZlmyvCsd21Ayj+/AtYjSBxJWcenaYVmX/T/nYVteJGlY0kam2VnCLGqAinasEu9ZfElwqUqKeA8ePoypi7FpcdQysh8k1p0lBlFm9afHwpffMeEpztjiprt//5MkJ04+QGKlndDykQK9 opentlc-mgr@admin.na.shared.opentlc.com
# pullSecret will be added from common/pull-secret.json
pullSecret: |
  __PULL_SECRET__